# Copyright 2023 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

extends:
  - stylelint-config-standard
  - stylelint-prettier/recommended
plugins:
  - stylelint-order
rules:
  color-hex-case: lower
  order/properties-alphabetical-order: true
  unit-disallowed-list:
    - 'px'
  selector-class-pattern: '^[a-zA-Z\-]+$'
  rule-empty-line-before: never
