# Copyright 2022 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM node:16.15.1-alpine3.16

WORKDIR /workspace/cmd/relui
