# Copyright 2021 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

FROM golang:1.23 AS build

COPY go.mod /app/go.mod
COPY go.sum /app/go.sum

WORKDIR /app

RUN go mod download

COPY . /app

RUN go build golang.org/x/build/cmd/relui

ENTRYPOINT go test -v ./cmd/relui/... ./internal/relui/... ./internal/workflow/...
