power8:
	./setup-remote.sh ubuntu@140.211.169.160 host-linux-ppc64le-osu

power9:
	./setup-remote.sh ubuntu@140.211.169.171 host-linux-ppc64le-power9-osu

power10:
	./setup-remote.sh ubuntu@go-le-p10-1.osuosl.org host-linux-ppc64le-power10-osu
