# Copyright 2022 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: gitmirror-mirroring-deployment
  labels:
    app: gitmirror-mirroring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitmirror-mirroring
  template:
    metadata:
      labels:
        app: gitmirror-mirroring
    spec:
      serviceAccountName: gitmirror
      volumes:
      - name: cache-volume
        emptyDir:
          medium: Memory
      containers:
      - name: gitmirror
        image: gcr.io/symbolic-datum-552/gitmirror:latest
        imagePullPolicy: Always
        env:
        - name: XDG_CACHE_HOME
          value: "/cache"
        command: ["/usr/bin/tini", "--", "/gitmirror", "-http=:8585", "-mirror=true", "-cachedir=/cache/gitmirror"]
        volumeMounts:
        - mountPath: /cache
          name: cache-volume
        ports:
        - containerPort: 8585
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8585
          initialDelaySeconds: 600
          failureThreshold: 60
          periodSeconds: 10
        resources:
          requests:
            cpu: "4"
            memory: "10Gi"
          limits:
            cpu: "6"
            memory: "12Gi"
