# Copyright 2022 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: coordinator-deployment
spec:
  selector:
    matchLabels:
      app: coordinator
  template:
    metadata:
      labels:
        app: coordinator
    spec:
      containers:
      - name: coordinator
        image: gcr.io/go-dashboard-dev/coordinator:latest
        imagePullPolicy: Always
        command: ["/coordinator"]
        securityContext:
          seccompProfile:
            type: RuntimeDefault
          appArmorProfile:
            type: RuntimeDefault
        ports:
        - containerPort: 80
        - containerPort: 443
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "3"
            memory: "6Gi"
