# Copyright 2017 The Go Authors. All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.
FROM golang:1.8
LABEL maintainer "golang-dev@googlegroups.com"

RUN go get -d github.com/aclements/go-gg/generic/slice && \
    go get -d github.com/aclements/go-gg/gg && \
    go get -d github.com/aclements/go-gg/ggstat && \
    go get -d github.com/aclements/go-gg/table && \
    cd /go/src/github.com/aclements/go-gg && git reset --hard abd1f791f5ee99465ee7cffe771436379d6cee5a

RUN go get -d github.com/aclements/go-moremath/stats && \
    cd /go/src/github.com/aclements/go-moremath && git reset --hard 033754ab1fee508c9f98f2785eec2365964e0b05

RUN go get -d github.com/google/go-github/github && \
    cd /go/src/github.com/google/go-github && git reset --hard 7a51fb928f52a196d5f31daefb8a489453ef54ff

RUN go get -d github.com/kylelemons/godebug/pretty && \
    cd /go/src/github.com/kylelemons/godebug && git reset --hard a616ab194758ae0a11290d87ca46ee8c440117b0

RUN go get -d golang.org/x/net/context && \
    cd /go/src/golang.org/x/net && git reset --hard fe686d45ea04bc1bd4eff6a52865ce8757320325

RUN go get -d golang.org/x/oauth2 && \
    cd /go/src/golang.org/x/oauth2 && git reset --hard f047394b6d14284165300fd82dad67edb3a4d7f6

RUN go get -d golang.org/x/sync/errgroup && \
    cd /go/src/golang.org/x/sync && git reset --hard f52d1811a62927559de87708c8913c1650ce4f26

# Optimization to speed COPY+go install steps later. This go install
# isn't required for correctness.
RUN go install github.com/aclements/go-gg/generic/slice \
    github.com/aclements/go-gg/gg \
    github.com/aclements/go-gg/ggstat \
    github.com/aclements/go-gg/table \
    github.com/aclements/go-moremath/stats \
    github.com/google/go-github/github \
    github.com/kylelemons/godebug/pretty \
    golang.org/x/net/context \
    golang.org/x/oauth2 \
    golang.org/x/sync/errgroup

COPY . /go/src/golang.org/x/build/

RUN go install -ldflags "-linkmode=external -extldflags '-static -pthread'" golang.org/x/build/devapp/devappserver